In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#read dataset
df=pd.read_csv("weather_forecast_data (1).csv")
#display the first 5 rows
df.head()

   Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0    23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1    27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2    25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3    23.622080  74.367758    7.050551    67.255282   982.632013     rain
4    20.591370  96.858822    4.643921    47.676444   980.825142  no rain

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  2500 non-null   float64
 1   Humidity     2500 non-null   float64
 2   Wind_Speed   2500 non-null   float64
 3   Cloud_Cover  2500 non-null   float64
 4   Pressure     2500 non-null   float64
 5   Rain         2500 non-null   object
dtypes: float64(5), object(1)
memory usage: 117.3+ KB

       Temperature     Humidity   Wind_Speed  Cloud_Cover     Pressure
count  2500.000000  2500.000000  2500.000000  2500.000000  2500.000000
mean     22.581725    64.347094     9.906255    49.658104  1014.312336
std       7.326996    19.954739     5.780316    29.123104    20.196433
min      10.001842    30.005071     0.009819     0.015038   980.014486
25%      16.359398    47.339815     4.761909    23.900016   996.938630
50%      22.536448    63.920797     9.908572    49.488284  1013.433035
75%      28.976476    81.561021    14.948408    75.324140  1031.735067
max      34.995214    99.997481    19.999132    99.997795  1049.985593

In [3]:
encoder = LabelEncoder()
df["Rain"]= encoder.fit_transform(df["Rain"])
df.head()

   Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure  Rain
0    23.720338  89.592641    7.335604    50.501694  1032.378759     1
1    27.879734  46.489704    5.952484     4.990053   992.614190     0
2    25.069084  83.072843    1.371992    14.855784  1007.231620     0
3    23.622080  74.367758    7.050551    67.255282   982.632013     1
4    20.591370  96.858822    4.643921    47.676444   980.825142     0

In [4]:
x=df.drop("Rain",axis=1)
y=df["Rain"]

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [7]:
y_pred=model.predict(x_test)

In [8]:
accuracy=accuracy_score(y_test, y_pred)
print("\nClassification Report")
print(classification_report(y_test,y_pred))
print("\nconfusion matrix")
print(confusion_matrix(y_test,y_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       443
           1       0.73      0.65      0.69        57

    accuracy                           0.93       500
   macro avg       0.84      0.81      0.82       500
weighted avg       0.93      0.93      0.93       500


confusion matrix
[[429  14]
 [ 20  37]]

In [9]:
sample=[[25, 80, 5, 60, 1015]]
prediction=model.predict(sample)
if prediction[0]==1:
    print("Prediction: Rain")
else:
    print("Prediction: No Rain")

Prediction: No Rain

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(